on: [push, pull_request]
name: Publish
jobs:
  publish:
    name: Publish
    runs-on: linux
    if: false && github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) # <- This make sure the workflow is skipped without any alert
    steps:
    - uses: actions/checkout@v4
    - name: Build
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install && npm run build
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
